### ISSUE TITLE
Scheduled transactions not loading

### ISSUE THREAD

**Issue by kennym** [chronologic/eth-alarm-clock-dapp#202]
https://app.chronologic.network/transactions/scheduled returns a 404

Steps to reproduce:

1) Create a new scheduled transaction
2) Go to scheduled transactions page (https://app.chronologic.network/transactions/scheduled)
3) Does not finish loading due to 404

**Comment by kennym** [comment]
OK, they do load - but sometimes it takes longer than 20 seconds, and I also still get the 404 always.

**Comment by Bagaric** [comment]
Thanks for submitting the problem @kennym.
There are some performance optimizations at work. Some of them have already been pushed to the `develop` branch, but more will be included in the release.

**Comment by Bagaric** [comment]
We'll leave it open for now until the issue if fixed.

**Comment by adibas03** [comment]
PR to reslove this :
https://github.com/chronologic/eth-alarm-clock-dapp/pull/218

**Comment by kennym** [comment]
I've just tested the latest changes on `develop`... scheduled transactions aren't loading for me anymore, or are very slow. Waiting 5+ minutes here and still nothing.

**Comment by kennym** [comment]
Completed transactions almost load instantly... good job on that 👍
