### ISSUE TITLE
Incorrect "Total amount" shown when scheduling a transaction

### ISSUE THREAD

**Issue by kennym** [chronologic/eth-alarm-clock-dapp#203]
Tested on Kovan.

Chrons DApp shows 0.52005 ETH while MetaMask shows 0.52155 ETH. Missing Gas information?

![image](https://user-images.githubusercontent.com/160117/37463238-5d59ca02-2833-11e8-889a-ddc262358798.png)

**Comment by adibas03** [comment]
Hey @kennym 
The total amount is the actual value being sent to the transaction.
The gas cost for submitting the transaction is as such not added.

**Comment by adibas03** [comment]
closing this, now.
