### ISSUE TITLE
Timenode creation reset

### ISSUE THREAD

**Issue by kennym** [chronologic/eth-alarm-clock-dapp#204]
Currently when you submit a wallet file for creating a Timenode there is no way for a user to reset the process so he can try submitting another wallet file.

I would like to try again with another wallet in case the current one doesn't work.

The only way currently is to clear all local storage via the developer console.

![image](https://user-images.githubusercontent.com/160117/37463925-76cdd4ea-2835-11e8-9364-34175ddda54f.png)

**Comment by Bagaric** [comment]
Thanks for submitting the issue @kennym.
We'll be implementing a `Delete` button for unassigning the wallet from the TimeNode into the next release.
