### ISSUE TITLE
Are there periodic verifications a Timenode has enough DAY after creation?

### ISSUE THREAD

**Issue by kennym** [chronologic/eth-alarm-clock-dapp#211]
Once someone signs to verify they have enough day in their wallet to run a time node how do you confirm they keep Day in that wallet. Are there periodic verifications?

**Comment by Bagaric** [comment]
Hi @kennym, yes there is a periodic check (5s at the moment) for DAY tokens. 

The tokens do not have to be on the same wallet as the imported TimeNode wallet. The user can use any wallet to sign the message during the TimeNode creation procedure. The address which they used to sign the message is then stored (encrypted) and the DAY balance of that address is checked periodically.
