### ISSUE TITLE
Repeated messages not disappearing after a new notification

### ISSUE THREAD

**Issue by kennym** [chronologic/eth-alarm-clock-dapp#229]
Steps to reproduce:

1) Go to app.chronologic.network
2) Make sure you're logged in with Metamask
3) Change your wallet an arbitrary number of times
4) Request test DAY from faucet
5) Voilá, you get this:

![image](https://user-images.githubusercontent.com/160117/38308402-fe1fb5d0-37e4-11e8-899a-110a2ecddd5d.png)

Those notifications don't go away unless you click them away.

**Comment by Bagaric** [comment]
Hi @kennym thanks for reporting the issue. I've run into this issue a couple of times but didn't manage to recreate the bug to find the cause. Adding a timeout to the notification is only a workaround though. We'll look into this and see why that happens!

**Comment by kennym** [comment]
@Bagaric it probably happens because of this: https://github.com/chronologic/eth-alarm-clock-dapp/blob/master/app/services/notification.js#L11

So, I think adding the timeout explicitly might be a valid solution.

**Comment by kennym** [comment]
https://github.com/chronologic/eth-alarm-clock-dapp/blob/master/app/services/notification.js#L11

The bug is probably that in that line you set the timeout to 0 if the notification type is not `success`.

**Comment by Bagaric** [comment]
@kennym You are correct. I misunderstood the issue you've been having - lets merge your changes.
