### ISSUE TITLE
[BUG] Negative balance after running timenode for a week

### ISSUE THREAD

**Issue by kennym** [chronologic/eth-alarm-clock-dapp#232]
This is an issue from a user who posted this in our Discord channel:

"I have a question... i've run a timenode in a browser properly for a week now since i detached my wallet and renewed proving ownership because i was a ghost timenode for a while,  so far i have 1 claimed transaction:  https://i.imgur.com/u20QGVA.png

i renewed the page, so i can't make a screenshot of the log anymore, but it had a few failed claimed transactions that have cost me gas (i can see that in etherscan)
the amount in gas total (of about 8 failed claimed txs) is more than the bounty i received so far..."

I think you'll understand better what's been happening here after seeing the screenshot

**Comment by kennym** [comment]
The timenode wallet in question is: 0x504777f5a5a0e4102a4193c4e60d44d7e7e70dae

**Comment by kennym** [comment]
Additional data:

https://media.discordapp.net/attachments/431190842259013642/431364025511706644/TimeNode_Execution_Failed.png

https://media.discordapp.net/attachments/431190842259013642/431364107229462530/TimeNode_Execution_Failed_Etherscan.png

**Comment by adibas03** [comment]
This is an issue when the Timenode claims a transaction, but does not actually execute the transaction within the claimed window of the execution window, as a result, the node looses the claim to the node which finally executes such a transaction.
We are presently working on providing for latency and other related issues.

**Comment by kosecki123** [comment]
There are 2 major components that aim to mitigate this situation:

- [ ] Economic Strategy - that allows to set profitability threshold and control your risk exposure
- [ ] Incoming Transaction Detection (in works) - this aims to improve potential collision detetion
