### ISSUE TITLE
Cant sign proof of day token from Trezor

### ISSUE THREAD

**Issue by pdidge** [chronologic/eth-alarm-clock-dapp#250]
When trying to setup a time-node and following instructions to sign ownership of day tokens you are told to use a Metamask account. I have a time-mint on a Trezor hardware wallet and definitely don't want to import private keys to Metamask. If I try to sign directly from Trezor it comes up as invalid. Works find from Metamask. thanks.

**Comment by pdidge** [comment]
Hi Joseph,
I was following "How to Prove Day Ownership to be a Timenode" blog.

Had Trezor plugged in
I created a new wallet at MyCrypto and saved the Keystore file locally
Went to app.chronologic.network/timenode
selected wallet file and entered password - Unlocked wallet
copied message from step 2
followed hyperlink in step 1 to "https://www.mycrypto.com/signmsg.html"
pasted message into mycrypto message box
selected 'Trezor' radio button. selected 'Connect to Trezor'.
Entered PIN and passphrase
Selected address containing time-mint and DAY tokens (also has some ETH in
that wallet). Pressed 'Unlock Wallet'
Pressed 'Sign Message', physically confirmed on Trezor. Entered Passphrase.
Got Message Signature. Copied this entirely including start:end Brackets
Pasted signature into  https://www.mycrypto.com/signmsg.html as instructed.
Pressed 'Verify'
Get 'Invalid Signature' message at right of screen.


I have tried out the procedure exactly as described in the blog using a
temporary metamask account and it worked perfectly. I'm just not going to
import any private keys to Metamask or anywhere else so at the moment
either have to transfer day to Metamask and lose minting or keep in Trezor
and don't have a timenode.

Hope this helps. If you need any more info. please just shoot me an email.
kind regards, Craig.

**Comment by Bagaric** [comment]
Hi @pdidge, thanks for the awesomely detailed procedure. That procedure should work fine.
At the moment we are only active on the Kovan testnet. Mainnet release is coming soon.

Can you confirm that you have DAY/TimeMint on the Kovan testnet address?

If you need Kovan testnet DAY tokens, you can use the [faucet](https://app.chronologic.network/faucet) to get some.

**Comment by pdidge** [comment]
Makes sense now you say it. Forgot you can’t set to kovan when signing
direct from hardware wallet. Thanks or the follow up and reply Joseph.

**Comment by pdidge** [comment]
Ok, thanks Joseph. Appreciate the updates.

**Comment by pdidge** [comment]
Hey Joseph
Was there any progress on setting up a timenode and signing on a trezor
rather than metamask? Thanks

**Comment by kosecki123** [comment]
Looks like MyCrypto has signing using Trezor disabled at the moment.

<img width="1127" alt="untitled" src="https://user-images.githubusercontent.com/5417665/44094331-27978a74-9fd6-11e8-82a6-4f7e84630d4a.png">

As a workaround I was able to sign the message using MetaMask with Trezor (this is still hot). Follow this guide https://medium.com/metamask/trezor-integration-in-metamask-a8eaeae7f499

**Comment by pdidge** [comment]
Thanks Piotr. Will give it a shot
