### ISSUE TITLE
[BUG] Wonky stats for timenode

### ISSUE THREAD

**Issue by kennym** [chronologic/eth-alarm-clock-dapp#305]
Kovan address of timenode: 0x504777f5a5a0e4102a4193c4e60d44d7e7e70dae

![image](https://user-images.githubusercontent.com/160117/40677544-fbad3c0e-634b-11e8-9b15-f5c4ff1d9e3b.png)

Other commentary from user:

> another point i have by the way is that after running the timenode for a few days, switching from the LOGS tab back to STATISTICS in chrome browser takes up a lot of time, can be many minutes, and chrome is using a whole CPU core at 100%... it has to do with rendering the 'executed' graph, which is the only element in the web app that doesn't show while the web app is lagging

**Comment by lsaether** [comment]
Thanks @kennym 

Looks like there are forgotten `parseInt()`s somewhere. Will fix before the next release.

**Comment by Bagaric** [comment]
Thanks for reporting @kennym. Fixed in https://github.com/chronologic/eth-alarm-clock-dapp/pull/300 and will be live with the next release. Closing this issue.
