### ISSUE TITLE
Please add timestamp to .eac.log

### ISSUE THREAD

**Issue by TheNextLevel** [chronologic/eth-alarm-clock-dapp#309]
Testing the eac.js.cli. It writes log entries w/o date/time in front, which makes it hard do evaluate.

**Comment by lsaether** [comment]
:+1: This is more for eac.js which handles all of the logging functionality. It's a pretty simple addition. I'm currently neck-deep in some refactoring on that front. I will include this while I'm at it.

**Comment by Bagaric** [comment]
Solved. Closing.

**Comment by TheNextLevel** [comment]
[info] EAC-TimeNode
[info] Version: 4.2.5
[info] Watching ENABLED
Still no Timestamp ...

**Comment by Kuzirashi** [comment]
![9e0477cb64411b9d0f412b6575c81bb4](https://user-images.githubusercontent.com/4950658/43159863-dd2a7846-8f83-11e8-9b68-1d9e5e7c5b54.png)

@TheNextLevel
