### ISSUE TITLE
TimeNode DAY balance is always taken from the MetaMask network

### ISSUE THREAD

**Issue by Bagaric** [chronologic/eth-alarm-clock-dapp#612]
**Reproduction steps:**
1. Open the dapp and unlock your MetaMask account
2. Set the MetaMask network to Mainnet
3. Setup a TimeNode and set the TimeNode provider to be Kovan
4. The TimeNode screen will correctly read your ETH balance but will show the Mainnet DAY balance
5. Set the MetaMask network to Kovan and it should be working properly

**Expected behaviour:**
TimeNode should always display the DAY balance of the TimeNode-specific web3 provider and not MetaMask-injected web3 provider.

**Comment by adibas03** [comment]
COnnected to https://github.com/chronologic/eth-alarm-clock-dapp/pull/611

**Comment by Bagaric** [comment]
Separate issue but of the same nature.

**Comment by Bagaric** [comment]
Fixed in https://github.com/chronologic/eth-alarm-clock-dapp/pull/613.
