### ISSUE TITLE
Claimed but didn´t execute

### ISSUE THREAD

**Issue by alancampeao1** [chronologic/eth-alarm-clock-dapp#696]
My TN claimed a few transactions but didn´t execute them for no clear reason. Internet was stable. Lost a few ETH from the failed TX, just wondering why.

Here are the logs for one of the failed TX that made me loose ETH (22:51:28):

14/09/2018 22:51:14 [DEBUG] 0xb50f2582f65e93de043e9bad205c30bb8e1a83f3 Transitioning from BeforeClaimWindow to ClaimWindow (1)
14/09/2018 22:51:15 [DEBUG] txRequestClaimed=0xaf8498dd1c0fd3e885a43821fbddc0b9d2e681ad,0xb50f2582f65e93de043e9bad205c30bb8e1a83f3
14/09/2018 22:51:16 [INFO] 0xb50f2582f65e93de043e9bad205c30bb8e1a83f3 Claiming...
14/09/2018 22:51:18 [DEBUG] Tx: ["0x06","0x0165a0bc00","0x01d4c0","0xb50f2582f65e93de043e9bad205c30bb8e1a83f3","0x8e1bc9bf040000","0x4e71d92d","0x1c","0x5e73988be3a80822124c6a804f0872b51257c58409db638523544d8d1e87840b","0x5b2730aeb03d83c9dd562ebfa2e29e5c4b0c3c8fedbd3ff7138ff6b2675c8c67"]
14/09/2018 22:51:18 [DEBUG] 0xb50f2582f65e93de043e9bad205c30bb8e1a83f3 Transitioning from BeforeClaimWindow to ClaimWindow (1)
14/09/2018 22:51:22 [DEBUG] 0xb50f2582f65e93de043e9bad205c30bb8e1a83f3 Transitioning from BeforeClaimWindow to ClaimWindow (1)
14/09/2018 22:51:22 [DEBUG] txRequestClaimed=0xaf8498dd1c0fd3e885a43821fbddc0b9d2e681ad,0xb50f2582f65e93de043e9bad205c30bb8e1a83f3
14/09/2018 22:51:23 [DEBUG] txRequestClaimed=0xaf8498dd1c0fd3e885a43821fbddc0b9d2e681ad,0xb50f2582f65e93de043e9bad205c30bb8e1a83f3
14/09/2018 22:51:27 [DEBUG] txRequestClaimed=0xaf8498dd1c0fd3e885a43821fbddc0b9d2e681ad,0xb50f2582f65e93de043e9bad205c30bb8e1a83f3
14/09/2018 22:51:28 [DEBUG] Receipt: {"receipt":{"blockHash":null,"blockNumber":null,"contractAddress":null,"cumulativeGasUsed":202070,"gasUsed":22589,"logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","root":null,"status":"0x0","transactionHash":"0xa718abcd84bdca723978eed28f486a6b03b6d9686e702ec68cecda2e0b979c56","transactionIndex":5},"from":"0xcda1d46d2c4927144b990c8843c5ea77fc1e094e"}
14/09/2018 22:51:28 [ERROR] 0xb50f2582f65e93de043e9bad205c30bb8e1a83f3 Claiming: Transaction already claimed
14/09/2018 22:51:28 [DEBUG] 0xb50f2582f65e93de043e9bad205c30bb8e1a83f3 Transitioning from ClaimWindow to FreezePeriod (2)

![image](https://user-images.githubusercontent.com/7557459/45588115-dd064f80-b8e5-11e8-9274-aa0cae154a1d.png)

**Comment by alancampeao** [comment]
So you could say those 3 claimed but failed transactions have failed because the TN were mined in the uncle block?

**Comment by kosecki123** [comment]
```14/09/2018 22:51:28 [ERROR] 0xb50f2582f65e93de043e9bad205c30bb8e1a83f3 Claiming: Transaction already claimed```

This error means that your timenode collide with other node and unfortunately did not win.
