### ISSUE TITLE
Claimed, didn't execute, deposit returned but not updated

### ISSUE THREAD

**Issue by johnbassplayer** [chronologic/eth-alarm-clock-dapp#699]
@lsaether

This is the claim that didn't execute and deposit didn't update when returned:

![2018-09-15 7](https://user-images.githubusercontent.com/40284141/45588214-1bf9cc80-b909-11e8-8319-5f60b60de97d.png)

![2018-09-15 1](https://user-images.githubusercontent.com/40284141/45588211-169c8200-b909-11e8-9154-c8055b0f8c1b.png)

This keeps intermittently happening:

   14/09/2018 21:01:50 [DEBUG] Buckets: Watcher for bucket=1536955200 has been stopped

   14/09/2018 21:01:50 [DEBUG] Buckets: Watcher for bucket=1536958800 has been started

This happened since 7AM GMT:

   15/09/2018 16:31:47 [DEBUG] Invalid log message format: {} is not a string.

Here's the logs:

[logtm15092018.txt](https://github.com/chronologic/eth-alarm-clock-dapp/files/2385877/logtm15092018.txt)

[logtm15092018basic.txt](https://github.com/chronologic/eth-alarm-clock-dapp/files/2385878/logtm15092018basic.txt)

My signed message has space in it, is this relevant?:
Timenode 0x2ca4a62baa04361b4c9ab2127e457ba862b4d917

Reloaded client in browser and found that response to even show balance and start timenode taken considerably longer than usual (towards a minute this time).

**Comment by johnbassplayer** [comment]
Weird empty logs again.

[logtm17092018.txt](https://github.com/chronologic/eth-alarm-clock-dapp/files/2390530/logtm17092018.txt)

**Comment by lsaether** [comment]
Investigating into this, it seemed these error messages: `Invalid log message format: {} is not a string.` first showed up here ethereum-alarm-clock/ethereum-alarm-clock#174 

Investigating into this now.

**Comment by johnbassplayer** [comment]
...continued like this since last time

_18/09/2018 23:10:20 [DEBUG] Invalid log message format: {} is not a string._

    then I

18/09/2018 23:10:54 [INFO] Scanner STOPPED

18/09/2018 23:10:54 [DEBUG] Invalid log message format: {} is not a string.

18/09/2018 23:10:54 [DEBUG] Invalid log message format: {} is not a string.

   On the 2nd time check out the bucket number in bold

18/09/2018 23:10:54 [DEBUG] TxPool STOPPED

18/09/2018 23:10:54 [ERROR] Buckets: Stopping bucket=-6350160 watching failed!

18/09/2018 23:10:54 [ERROR] Buckets: Stopping bucket=**1537214400** watching failed!

Doesn't look right.

**Comment by kosecki123** [comment]
This should be fixed in #751
