### ISSUE TITLE
Discovered Transactions value only updates on Stop Start of TimeNode

### ISSUE THREAD

**Issue by cryogenn** [chronologic/eth-alarm-clock-dapp#710]
Hi - I'm seeing an issue on the website where the Discovered Transactions value only updates if you Stop and Start the TimeNode. My assumption is that this is a bug or an oversight because I am under the impression that the Dashboard would contain automatically updated and accurate information. If this is how it was designed to work, I think it is mis-leading because the Active TimeNodes value in the header updates automatically, so one would assume that all the other data would update automatically on the website. If you need logs and screenshots let me know (and I did make an attempt to try and generate them) but there were no new Discovered Transactions at the time of writing this to show that the value only updates with a Stop/Start but not when you Refresh the page. The issue was raised by someone else in Telegram originally, but I also noticed after trying it myself.

This is on Mainnet.

**Comment by cryogenn** [comment]
I'm not sure if this is an issue anymore, I have stopped using the browser and have switched to the Windows desktop installer. Feel free to close it out if unable to replicate.

**Comment by kosecki123** [comment]
I've just tested using Version 1.1.1 (1.1.1.4564). Discovered transaction autoupdates.
