### ISSUE TITLE
TimeNode becomes unresponsive after a longer minimized period

### ISSUE THREAD

**Issue by TheNextLevel** [chronologic/eth-alarm-clock-dapp#715]
I've noticed, that this is since the first Dapp version anyway, but did not care yet.

I'm running the Windows timenode app, change to the log tab and minimize the window.

If I restore the window a few hours later and switch to the statistics tab, the UI becomes unresponsive, CPU goes up and the memory consumption starts to climb constantly forever. But I can close the TN normally with the X button.

![image](https://user-images.githubusercontent.com/31387914/45754043-d98f0300-bc1a-11e8-92d1-59749687febe.png)

The same thing happens when I start a timenode using chrome from https://app.chronologic.network/timenode

**Comment by TheNextLevel** [comment]
With version 5.3.0, this issue seems too be vanished.

**Comment by kosecki123** [comment]
> With version V1.1.0 / 5.3.0, this issue seems to be vanished.

Closing the issue then. 

Let us know if it re-appears.
