### ISSUE TITLE
Something is seriously wrong at the moment

### ISSUE THREAD

**Issue by AutonomousSystems** [chronologic/eth-alarm-clock-dapp#731]
The contracts, schedulers and libraries aren't available/connecting right now.
The browser app is showing a blank screen when metamask isn't active and when it is active the amount of timenodes isn't showing and it doesn't change to kovan or ropsten when being told to do so via metamask.
When recreating a TimeNode through the dapp it can't go past the 'unlock' button, i assume because there is no connection possible with the contracts/schedulers/libraries somehow.
In case this is caused by human error; please set up some automated test procedures for the vital parts of the whole operation before and after pushing an updated version to mainnet. If this is caused by something out of CL's control, i apologize..

**Comment by Kuzirashi** [comment]
https://app.chronologic.network/ should be working now.

There was a human error when releasing. Increasing automated test coverage is we have in mind.
