### ISSUE TITLE
Active Timenodes value goes away in Windows Desktop v1.1.2

### ISSUE THREAD

**Issue by cryogenn** [chronologic/eth-alarm-clock-dapp#802]
I did not notice this in prior builds (so I am going to assume this is a new bug) but the value next to Active TimeNodes does not always show up. Instead it has the yellow button with the information text. I know the button shows up if you're using the browser and you have tracking blocked but since this is the desktop application I wouldn't expect the issue to come up.

The number does reappear if you reload the page but the number should be there all the time in my opinion like it used to be.

![01 active timenodes number](https://user-images.githubusercontent.com/19438657/46922462-86b92900-cfd7-11e8-92c0-4c959cc529df.png)
![02 message in icon](https://user-images.githubusercontent.com/19438657/46922463-86b92900-cfd7-11e8-8824-6610e104e4f1.png)

**Comment by kosecki123** [comment]
I've tested on my Windows 10 machine and it works well.

![image](https://user-images.githubusercontent.com/5417665/46999415-eb829980-d125-11e8-9c16-92bc76f84165.png)

**Comment by Bagaric** [comment]
@cryogenn Could you provide more information on your specific Windows installation? Might help us locate the problem.

Edition:
Version:
OS Build:
System Type:

You can find those in Settings -> System -> About.

**Comment by cryogenn** [comment]
Attached is the info you asked for.

I doubt there is a firewall issue because when I restarted my machine I saw the Active TimeNodes value populate, that was 9 hours ago. But as I write this, the value has disappeared again. I haven't used the laptop for anything else except to run the Chronos desktop app within that timeframe.

![windows 10 info](https://user-images.githubusercontent.com/19438657/47001959-b06a7100-d0f9-11e8-9a01-3deccd00ddc8.png)

**Comment by cryogenn** [comment]
I'm not seeing any Chronos or TimeNode related entries in the Windows firewall application (numbers 1 through 4) but the TimeNode is running (number 5)

![01 inbound chronos](https://user-images.githubusercontent.com/19438657/47002917-25d74100-d0fc-11e8-9905-7532d149d39d.png)
![02 inbound timenode](https://user-images.githubusercontent.com/19438657/47002918-266fd780-d0fc-11e8-9a00-a17354efef7e.png)
![03 outbound chronos](https://user-images.githubusercontent.com/19438657/47002919-266fd780-d0fc-11e8-9645-9ecb5b1e599b.png)
![04 outbound timenode](https://user-images.githubusercontent.com/19438657/47002920-266fd780-d0fc-11e8-922e-3f7cf3ff565f.png)
![05 timenode in task manager](https://user-images.githubusercontent.com/19438657/47002921-266fd780-d0fc-11e8-99b5-4a98ad921277.png)

**Comment by cryogenn** [comment]
To be clear, I only have one copy of the TimeNode executable running on my actual desktop. I'm not sure why it shows up as using 3 processes inside the Task Manager.

**Comment by cryogenn** [comment]
This issue hasn't come up on v1.1.3 even after running it for over 24 hours. On 1.1.2 it would show up much faster (within 12 hours). From my side I'm all set but will monitor it over the week to see if the problem shows up again.

**Comment by cryogenn** [comment]
The issue is still there, guess it took a little longer to show up. 3 days or so.

![active timenodes on v1 1 3](https://user-images.githubusercontent.com/19438657/47303367-b5478d00-d5f1-11e8-8d9c-3895d288415d.png)

**Comment by cryogenn** [comment]
Seems to be working properly in v1.2.0
