### ISSUE TITLE
Windows TimeNode update runs twice v1.1.2 to 1.1.3

### ISSUE THREAD

**Issue by cryogenn** [chronologic/eth-alarm-clock-dapp#818]
Hi - the automatic update to the software on Windows ran twice. Nothing major but wanted to report it since that looked odd.

So I launched the current version manually since I had to restart my machine, version 1.1.2, and it gave the prompt that an update was available. It downloaded, installed and asked if I wanted to restart the software. I restarted and it brought up the attached with the v1.1.3 release notes. However it also notified me again that it needed to update for a second time.

My assumption would be that after seeing the screen with the v1.1.3 release notes, I would then continue to use the program and not have to restart the application again.

If it was meant to restart twice by design, you might want to make the second prompt say that the app needs to restart again in order to complete installation.

![timenode update](https://user-images.githubusercontent.com/19438657/47225847-099e0300-d38d-11e8-8852-41d43a8da2bf.png)

**Comment by Bagaric** [comment]
Thanks for the update @cryogenn! We were not able to replicate this issue, but if it happens again we can reopen this issue. Closing for now.
