### ISSUE TITLE
How to whitelist site?

### ISSUE THREAD

**Issue by housemobile** [chronologic/eth-alarm-clock-dapp#843]
To see active timenodes, the dapp says to whitelist the site. I can't find information anywhere on this. How does one whitelist the site?

**Comment by Bagaric** [comment]
Hi @housemobile. Are you running any privacy software such as Ghostery or DuckDuckGo Privacy Essentials? If so, they are probably the ones blocking the analytics so you should check the settings in those plugins to whitelist https://app.chronologic.network.
