### ISSUE TITLE
Unable to load the completed view

### ISSUE THREAD

**Issue by kosecki123** [chronologic/eth-alarm-clock-dapp#905]
When using no-web3 enabled browser, it's impossible to load the completed page.

![image](https://user-images.githubusercontent.com/5417665/49785677-9cba4000-fd21-11e8-9b2e-cb687add6d8e.png)

**Comment by Kuzirashi** [comment]
Just wanted to note that it wasn't working on Safari, while on Chrome without MetaMask it was working.
