### ISSUE TITLE
Connection not open after 1.3.0 installation

### ISSUE THREAD

**Issue by baltcoinh** [chronologic/eth-alarm-clock-dapp#966]
SInce I installed v1.3.0, this error:
19/01/2019 07:37:58 [DEBUG] [WS ERROR] Error: connection not open
Is continuously appearing in my detailed debug log. With the same security configuration it didn't appear with the 1.2.1, 1.2.2 and 1.2.3 versions.
Operating in Mainnet over windows10 with native firewall and emsisoft security software.
Salute

**Comment by baltcoinh** [comment]
Maybe related with windows firewall, after deleting the rule allowing Timenode.exe to connect in private networks, message have dissapeared.

**Comment by baltcoinh** [comment]
After some hours running, error has reappeared. Main messages in debug.log (attached)
[DEBUG]  Invalid log message format: {} is not a string.
[ERROR]  Invalid providerUrl! eth_getFilterLogs not enabled.
[WS ERROR] Error: connection not open

[timenode.txt](https://github.com/chronologic/eth-alarm-clock-dapp/files/2776364/timenode.txt)

**Comment by housemobile** [comment]
1.3.0 won't connect with Ubuntu either

**Comment by Kuzirashi** [comment]
@baltcoinh @housemobile 

Do you still experience this problem? It's possible our Quiknode node started to randomly fail.

**Comment by baltcoinh** [comment]
Yes, Have tried a while ago and I continue reciving these lines in debug log:
21/01/2019 14:20:30 [DEBUG] Attempting WS Reconnect.
21/01/2019 14:20:31 [ERROR] Invalid providerUrl! eth_getFilterLogs not enabled.
21/01/2019 14:20:31 [INFO] Reconnect tries: 20

**Comment by kosecki123** [comment]
QuikNode issues have been fixed and node back to normal.

Read more here #968 on the next steps to improve the TimeNode operations.

**Comment by baltcoinh** [comment]
Hi Piotr,

Sorry about sendign you this info via email, but I don't want to spamming
github with other issue not being to sure about it being an issue or some
lack of understanding of the chronologic dapp working process.
I have the timenode address 0xb2f12bb423097248640ddDc7cED91a2EBF066809
working for about two months without too much success, 10 failed executions
and 2 failed and 3 successful claims. I have seen today live the claim
(successful) and execution (failed) process of a transaction from my tiime
node and I have some doubts.
Quite before the time window for the execution of 10 minutes ended (you can
see the chrono order here)
https://etherscan.io/address/0xb9d8e07058bebe60c69f888fdacfc892263676c0
the execution appeared as failed in my log, attached as timenode.log.30.
But strangest thing it's that my profit should be -0.1528 (0
bounties-0.1528 costs) but actually I have had a profit of 0.016 eth, you
can see the transaction history here
https://etherscan.io/address/0xb2f12bb423097248640dddc7ced91a2ebf066809
Not worried about the possible lost of profits, I know the project is in
development and I think is one of the few projects on the ethereum chain
with some real use cases, but I would love to know if the problem is
related with my configuration (not having a local ETH node, not having
white listed the needed addresses or something like that) that could help
to prepare a clearer manual of how to create a time node or is related with
some bug in the app that need to be addressed.
Thanks a lot for your attention and hope this help to improve the Dapp.
Kind regards
